# Generated by Django 3.2.15 on 2022-09-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_tags_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
