# Generated by Django 3.2.15 on 2022-09-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует'}, help_text='Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
